answers_num_default: 2
size_picture: "75x75"
size_avatar: "75x75"
per: 10
words_minimum: 2
admin_show_words: 21
deadline_minites: 11
users_show_lessons: 9
size_avatar_admin_show: "40"
admin_show_user: 7
size_picture_words_edit: 200

activities:
  learned: learned
  followed: followed
  unfollowed: unfollowed
  start_lesson: start lesson
